#!/usr/bin/python
from filter_packets import *
from packet_parser import *
from compute_metrics import *


L1 = []
L2 = []
L3 = []
L4 = []
x="\n"


filter()

parse("Node1_filtered.txt", L1)
parse("Node2_filtered.txt", L2)
parse("Node3_filtered.txt", L3)
parse("Node4_filtered.txt", L4)

(a,b,c,d,e,f,g,h,i,j,k,l,m) = compute("192.168.100.1",L1,"Node1_filtered.txt")

filename="miniproject2_output.csv"
file = open(filename,"w")
file.write("Node1")
file.write(x)
file.write("Echo Requests Sent" + "," + "Echo Requests Recieved" + "," + "Echo Replies Sent" + "," + "Echo Replies Recieved"+ x )
file.write(str(a)+","+str(b)+","+str(c)+","+str(d)+x)
file.write("Echo Request Bytes sent (bytes)" + "," + "Echo Request Data Sent (bytes)"+ x)
file.write(str(e)+","+str(f)+x)
file.write("Echo Request Bytes Recieved (bytes)" + "," + "Echo Request Data Recieved (bytes)"+x)
file.write(str(g)+","+str(h)+x)
file.write(x)
file.write("Average RTT (miliseconds)" + "," + str(i) + x)
file.write("Echo Request Throughput (kB/sec)" + "," + str(j) + x)
file.write("Echo Request Goodput (kB/sec)" + "," + str(k) + x)
file.write("Average Reply Delay (microseconds)" + "," + str(l) + x)
file.write("Average Echo Request Hop Count" + "," + str(m) + x)
file.write(x)
file.close()
(a,b,c,d,e,f,g,h,i,j,k,l,m) = compute("192.168.100.2",L2,"Node2_filtered.txt")
file = open(filename,"a")
file.write("Node2")
file.write(x)
file.write("Echo Requests Sent" + "," + "Echo Requests Recieved" + "," + "Echo Replies Sent" + "," + "Echo Replies Recieved"+ x )
file.write(str(a)+","+str(b)+","+str(c)+","+str(d)+x)
file.write("Echo Request Bytes sent (bytes)" + "," + "Echo Request Data Sent (bytes)"+ x)
file.write(str(e)+","+str(f)+x)
file.write("Echo Request Bytes Recieved (bytes)" + "," + "Echo Request Data Recieved (bytes)"+x)
file.write(str(g)+","+str(h)+x)
file.write(x)
file.write("Average RTT (miliseconds)" + "," + str(i) + x)
file.write("Echo Request Throughput (kB/sec)" + "," + str(j) + x)
file.write("Echo Request Goodput (kB/sec)" + "," + str(k) + x)
file.write("Average Reply Delay (microseconds)" + "," + str(l) + x)
file.write("Average Echo Request Hop Count" + "," + str(m) + x)
file.write(x)
file.close()
(a,b,c,d,e,f,g,h,i,j,k,l,m)= compute("192.168.200.1",L3,"Node3_filtered.txt")
file = open(filename,"a")
file.write("Node3")
file.write(x)
file.write("Echo Requests Sent" + "," + "Echo Requests Recieved" + "," + "Echo Replies Sent" + "," + "Echo Replies Recieved"+ x )
file.write(str(a)+","+str(b)+","+str(c)+","+str(d)+x)
file.write("Echo Request Bytes sent (bytes)" + "," + "Echo Request Data Sent (bytes)"+ x)
file.write(str(e)+","+str(f)+x)
file.write("Echo Request Bytes Recieved (bytes)" + "," + "Echo Request Data Recieved (bytes)"+x)
file.write(str(g)+","+str(h)+x)
file.write(x)
file.write("Average RTT (miliseconds)" + "," + str(i) + x)
file.write("Echo Request Throughput (kB/sec)" + "," + str(j) + x)
file.write("Echo Request Goodput (kB/sec)" + "," + str(k) + x)
file.write("Average Reply Delay (microseconds)" + "," + str(l) + x)
file.write("Average Echo Request Hop Count" + "," + str(m) + x)
file.write(x)
file.close()
(a,b,c,d,e,f,g,h,i,j,k,l,m) = compute("192.168.200.2",L4,"Node4_filtered.txt")
file = open(filename,"a")
file.write("Node4")
file.write(x)
file.write("Echo Requests Sent" + "," + "Echo Requests Recieved" + "," + "Echo Replies Sent" + "," + "Echo Replies Recieved"+ x )
file.write(str(a)+","+str(b)+","+str(c)+","+str(d)+x)
file.write("Echo Request Bytes sent (bytes)" + "," + "Echo Request Data Sent (bytes)"+ x)
file.write(str(e)+","+str(f)+x)
file.write("Echo Request Bytes Recieved (bytes)" + "," + "Echo Request Data Recieved (bytes)"+x)
file.write(str(g)+","+str(h)+x)
file.write(x)
file.write("Average RTT (miliseconds)" + "," + str(i) + x)
file.write("Echo Request Throughput (kB/sec)" + "," + str(j) + x)
file.write("Echo Request Goodput (kB/sec)" + "," + str(k) + x)
file.write("Average Reply Delay (microseconds)" + "," + str(l) + x)
file.write("Average Echo Request Hop Count" + "," + str(m) + x)
file.write(x)
file.close()
